import 'package:flutter/foundation.dart';
import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:open_filex/open_filex.dart'; 
import 'package:permission_handler/permission_handler.dart';
import 'package:intl/intl.dart';

class PdfService {


  static Future<void> generateMultiMonthSummaryReport({
    required String branch,
    required String year,
    required String section,
    required List<Map<String, dynamic>> monthReports, // {month: Str, workingDays: int, data: Map}
    required List<Map<String, String>> students,
  }) async {
    final pdf = pw.Document();

    // Fonts
    ByteData? fontRegular = await rootBundle.load("assets/fonts/Poppins-Regular.ttf").catchError((_) => rootBundle.load("assets/fonts/Inter-Regular.ttf").catchError((_) => null));
    ByteData? fontBold = await rootBundle.load("assets/fonts/Poppins-Bold.ttf").catchError((_) => rootBundle.load("assets/fonts/Inter-Bold.ttf").catchError((_) => null));
    final ttfRegular = fontRegular != null ? pw.Font.ttf(fontRegular) : pw.Font.courier();
    final ttfBold = fontBold != null ? pw.Font.ttf(fontBold) : pw.Font.courierBold();

    final now = DateTime.now();
    final formattedDate = DateFormat('dd-MMM-yyyy hh:mm a').format(now);

    final parsedMonths = monthReports.map((r) {
       final mStr = r['month'].toString();
       return mStr.split(' ')[0].substring(0, 3); // e.g., "Aug"
    }).toList();

    int totalOverallWorkingDays = monthReports.fold(0, (sum, r) => sum + (r['workingDays'] as int));

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape, 
        margin: const pw.EdgeInsets.all(30),
        header: (context) => _buildReportHeader(branch, year, section, "Combined Multi-Month", formattedDate, "SUM-MUL-01", ttfBold, ttfRegular),
        footer: (context) => _buildBottomFooter("SUM-MUL-01", context.pageNumber, 1, ttfRegular),
        build: (context) => [
          pw.SizedBox(height: 20),
          pw.Center(child: pw.Text("FINAL ATTENDANCE SUMMARY", style: pw.TextStyle(font: ttfBold, fontSize: 16, decoration: pw.TextDecoration.underline))),
          pw.SizedBox(height: 20),
          _buildMultiMonthSummaryTable(students, monthReports, parsedMonths, totalOverallWorkingDays, ttfBold, ttfRegular),
          pw.SizedBox(height: 30),
          _buildSignatureBlock(ttfBold, ttfRegular, formattedDate),
        ]
      )
    );

    await _saveAndLaunchPdf(pdf, "Summary_Report_${branch}_$section.pdf");
  }



  static pw.Widget _buildReportHeader(String branch, String year, String section, String month, String generatedOn, String reportId, pw.Font fontBold, pw.Font fontRegular) {
    return pw.Column(
      children: [
        // Grey Header Bar
        pw.Container(
          width: double.infinity,
          height: 25,
          color: PdfColors.grey300,
          alignment: pw.Alignment.center,
          child: pw.Text("ATTENDANCE MANAGEMENT REPORT", style: pw.TextStyle(font: fontBold, fontSize: 12, fontWeight: pw.FontWeight.bold))
        ),
        pw.SizedBox(height: 5),
        
        // Info Box
        pw.Container(
           decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.black, width: 0.5)),
           padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 8),
           child: pw.Row(
             crossAxisAlignment: pw.CrossAxisAlignment.start,
             children: [
               // Left Column
               pw.Expanded(
                 flex: 3,
                 child: pw.Column(
                   crossAxisAlignment: pw.CrossAxisAlignment.start,
                   children: [
                      _buildInfoRow("College:", "ALWARDAS POLYTECHNIC-GOPALAPATNAM", fontBold, fontRegular),
                      pw.SizedBox(height: 4),
                      _buildInfoRow("Branch:", branch, fontBold, fontRegular),
                      pw.SizedBox(height: 4),
                      _buildInfoRow("Year & Section:", "$year - $section", fontBold, fontRegular),
                      pw.SizedBox(height: 4),
                      _buildInfoRow("Period:", month, fontBold, fontRegular),
                   ]
                 )
               ),
               // Right Column
               pw.Expanded(
                 flex: 2,
                 child: pw.Column(
                   crossAxisAlignment: pw.CrossAxisAlignment.start,
                   children: [
                      _buildInfoRow("Generated On:", generatedOn, fontBold, fontRegular),
                      pw.SizedBox(height: 4),
                      _buildInfoRow("Generated By:", "HOD / Admin", fontBold, fontRegular),
                      pw.SizedBox(height: 4),
                      _buildInfoRow("Report ID:", reportId, fontBold, fontRegular),
                   ]
                 )
               )
             ]
           )
        ),
        pw.SizedBox(height: 8),
        pw.Center(child: pw.Text("Legend: P = Present | A = Absent | H = Holiday", style: pw.TextStyle(font: fontBold, fontSize: 10))),
        pw.Divider(thickness: 1.5, color: PdfColors.grey800),
        pw.SizedBox(height: 5),
      ]
    );
  }

  static pw.Widget _buildInfoRow(String label, String value, pw.Font fb, pw.Font fr) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(width: 80, child: pw.Text(label, style: pw.TextStyle(font: fb, fontSize: 9))),
        pw.Expanded(child: pw.Text(value, style: pw.TextStyle(font: fr, fontSize: 9)))
      ]
    );
  }


  static String _normalizeStatus(String? s) {
     if (s == null) return '';
     final up = s.toUpperCase();
     if (up.contains('ABSENT')) return 'A';
     if (up.contains('PRESENT')) return 'P';
     if (up.contains('HOLIDAY')) return 'H';
     return ''; 
  }



  static pw.Widget _summaryHeaderCell(String text, pw.Font font, {double height = 30}) {
    return pw.Container(
      height: height,
      padding: const pw.EdgeInsets.all(5),
      alignment: pw.Alignment.center,
      child: pw.Text(text, style: pw.TextStyle(font: font, fontSize: 9, fontWeight: pw.FontWeight.bold), textAlign: pw.TextAlign.center)
    );
  }

   static pw.Widget _buildMultiMonthSummaryTable(List<Map<String, String>> students, List<Map<String, dynamic>> monthReports, List<String> monthLabels, int totalWorkingDays, pw.Font fb, pw.Font fr) {
      double totalDaysDouble = totalWorkingDays.toDouble();

      return pw.Table(
        border: pw.TableBorder.all(color: PdfColors.black, width: 0.5),
        columnWidths: {
          0: const pw.FixedColumnWidth(100), 
          1: const pw.FlexColumnWidth(2.5), 
          for (int i=0; i<monthLabels.length; i++)
             (i+2): const pw.FlexColumnWidth(1),
          // Total and Percentage
          (monthLabels.length + 2): const pw.FixedColumnWidth(60),
          (monthLabels.length + 3): const pw.FixedColumnWidth(60),
        },
        children: [
          pw.TableRow(
            decoration: const pw.BoxDecoration(color: PdfColors.grey200),
            children: [
               _summaryHeaderCell("Student ID", fb, height: 40),
               _summaryHeaderCell("Student Name", fb, height: 40),
               for (String m in monthLabels)
                 _summaryHeaderCell(m.toUpperCase(), fb, height: 40),
               _summaryHeaderCell("TOTAL", fb, height: 40),
               _summaryHeaderCell("PERCENTAGE", fb, height: 40),
            ]
          ),
          for (var s in students)
            _buildMultiMonthRow(s, monthReports, monthLabels, totalDaysDouble, fb, fr)
        ]
      );
   }

   static pw.TableRow _buildMultiMonthRow(Map<String, String> student, List<Map<String, dynamic>> monthReports, List<String> monthLabels, double totalWorkingDays, pw.Font fb, pw.Font fr) {
      double overallPresent = 0;
      List<pw.Widget> monthCells = [];

      for (var report in monthReports) {
         Map<String, Map<String, Map<String, String>>> data = report['data'];
         int presentAM = 0;
         int presentPM = 0;

         data.forEach((day, studentsData) {
            if (studentsData.containsKey(student['id'])) {
                final sStatus = studentsData[student['id']]!;
                if (_normalizeStatus(sStatus['AM']) == 'P') presentAM++;
                if (_normalizeStatus(sStatus['PM']) == 'P') presentPM++;
            }
         });
         
         double mPresentDays = (presentAM + presentPM) / 2.0;
         overallPresent += mPresentDays;
         
         String disp = mPresentDays % 1 == 0 ? mPresentDays.toInt().toString() : mPresentDays.toStringAsFixed(1);
         monthCells.add(_centeredCell(disp, fr));
      }

      double percentage = totalWorkingDays > 0 ? (overallPresent / totalWorkingDays) * 100 : 0.0;
      String dispTotal = overallPresent % 1 == 0 ? overallPresent.toInt().toString() : overallPresent.toStringAsFixed(1);

      return pw.TableRow(
         children: [
            _centeredCell(student['id'] ?? '', fr),
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text(student['name']?.toUpperCase() ?? '', style: pw.TextStyle(font: fb, fontSize: 9))),
            ...monthCells,
            _centeredCell(dispTotal, fr),
            _centeredCell("${percentage.toStringAsFixed(2)}%", fb),
         ]
      );
   }

  static pw.Widget _centeredCell(String text, pw.Font font) {
     return pw.Container(
       height: 25,
       padding: const pw.EdgeInsets.all(2),
       alignment: pw.Alignment.center,
       child: pw.Text(text, style: pw.TextStyle(font: font, fontSize: 9))
     );
  }

  static pw.Widget _buildSignatureBlock(pw.Font fb, pw.Font fr, String date) {
     return pw.Column(
       children: [
         pw.Divider(thickness: 1, color: PdfColors.black),
         pw.SizedBox(height: 30),
         pw.Row(
           mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
           children: [
              _signatureLine("Class In-Charge Name:", fb),
              _signatureLine("Signature:", fb),
           ]
         ),
         pw.SizedBox(height: 30),
         pw.Row(
           mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
           children: [
              _signatureLine("HOD Name:", fb),
              pw.Row(children: [pw.Text("Date: ", style: pw.TextStyle(font: fb)), pw.Container(width: 120, decoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide())), child: pw.Text(""))])
           ]
         ),
       ]
     );
  }

  static pw.Widget _buildBottomFooter(String reportId, int pageNum, int totalPages, pw.Font font) {
     return pw.Container(
       width: double.infinity,
       margin: const pw.EdgeInsets.only(top: 10),
       child: pw.Column(
         children: [
            pw.Divider(thickness: 0.5, color: PdfColors.grey),
            pw.SizedBox(height: 5),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text("Report ID: $reportId", style: pw.TextStyle(font: font, fontSize: 8)),
                pw.Text("Page $pageNum of $totalPages", style: pw.TextStyle(font: font, fontSize: 8)),
              ]
            )
         ]
       )
     );
  }

  static pw.Widget _signatureLine(String label, pw.Font font) {
     return pw.Row(
       children: [
          pw.Text(label, style: pw.TextStyle(font: font, fontSize: 10, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(width: 10),
          pw.Container(width: 200, decoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide())), child: pw.Text(""))
       ]
     );
  }
  


  static Future<void> _saveAndLaunchPdf(pw.Document pdf, String fileName) async {
    try {
      if (Platform.isAndroid) {
        var status = await Permission.storage.status;
        if (!status.isGranted) {
           status = await Permission.storage.request();
           if (!status.isGranted && await Permission.manageExternalStorage.status.isDenied) {
                 await Permission.manageExternalStorage.request();
           }
        }
      }
      final dir = await getExternalStorageDirectory(); 
      String path = "${dir?.path ?? ''}/$fileName";
      final output = File(path);
      await output.writeAsBytes(await pdf.save());
      await OpenFilex.open(path);
    } catch (e) {
      debugPrint("Error saving PDF: $e");
    }
  }
}
