-- Obsolete migration: parent_student_links table does not exist in the codebase.
-- The actual table is parent_student and uses login_id (TEXT) instead of user_id (UUID),
-- so foreign key constraints to users(id) are not applicable.
